name: train

# training
steps: 10_000
warmup_steps: 500
batch_size: 4 
accumulate_grad_batches: 16

learning_rate: 0.0001

# architecture 
embed_dim: 512
num_heads: 8
num_layers: 24
num_pixels: 32
num_vocab: 512

classify: False

gpus: 1
precision: 16

block_size: 1023
attn_pdrop: 0.0
resid_pdrop: 0.0
embd_pdrop: 0.0

weight_decay: 0

image_create: False

